name: Issue Template
description: Standard issue template
body:
  - type: markdown
    attributes:
      value: |
        ## Relevans
        ### Niveau 1 – Lokal værdi
        Produktets relevans er, om det skaber lokal værdi og potentiel værdi for andre offentlige organisationer. Den lokale værdi være beskrevet og kunne overføres til andre.
  - type: checkboxes
    id: checkbox1
    attributes:
      label: Confirmation for Niveau 1
      options:
        - label: Løsningen skal skabe lokal værdi.
        - label: Løsningen skal have potentiel værdi for andre.
  - type: input
    id: input1
    attributes:
      label: Input for Niveau 1

  - type: markdown
    attributes:
      value: |
        ### Niveau 2 – Fælleskommunal værdi
        Værdien er nu ikke længere en potentiel værdi for andre organisationer, men en fælleskommunal værdi.
  - type: checkboxes
    id: checkbox2
    attributes:
      label: Confirmation for Niveau 2
      options:
        - label: Løsningen bør have et tværkommunal potentiale.
        - label: Accept fra lokal linjeledelse.
  - type: input
    id: input2
    attributes:
      label: Input for Niveau 2

  - type: markdown
    attributes:
      value: |
        ### Niveau 3 – Nationale strategier
        For N3 er gældende, at der skal være et ophæng til de nationale strategier. Det betyder, at produktet skal understøtte kommunerne i realisering af de kommunale krav og mål opstillet i de nationale strategier.
  - type: checkboxes
    id: checkbox3
    attributes:
      label: Confirmation for Niveau 3
      options:
        - label: Ophæng til nationale strategier er til stede.
  - type: input
    id: input3
    attributes:
      label: Input for Niveau 3
