name: Evaluering af produktniveau
description: OS2 arbejder med en tredelt governancemodel, der inddeler produkterne i tre niveauer ud fra organisatorisk og teknisk modenhedsniveau. 
body:
  - type: markdown
    attributes:
      value: |
        ## Relevans
  - type: checkboxes
    id: checkbox1
    attributes:
      label: Bekræft
      options:
        - label: Løsningen skaber lokal værdi.
  - type: input
    id: input1
    attributes:
      label: Hvordan skaber løsningen lokal værdi?
  - type: checkboxes
    id: checkbox2
    attributes:
      label: Bekræft
      options:
        - label: Løsningen skaber potentielt værdi for andre.
  - type: input
    id: input2
    attributes:
      label: Hvordan skaber løsningen potentielt værdi for andre?
  - type: checkboxes
    id: checkbox3
    attributes:
      label: Bekræft
      options:
        - label: Løsningen er accepteret af lokal linjeledelse.
  - type: input
    id: input3
    attributes:
      label: Hvordan er løsningen accepteret af lokal linjeledelse?
  - type: checkboxes
    id: checkbox4
    attributes:
      label: Bekræft
      options:
        - label: _Løsningen har tværkommunal potentiale (anbefaling)_.
  - type: input
    id: input4
    attributes:
      label: Hvordan har løsningen tværkommunal potentiale (anbefaling)?
  - type: checkboxes
    id: checkbox5
    attributes:
      label: Bekræft
      options:
        - label: Ophæng til nationale strategier er til stede.
  - type: input
    id: input5
    attributes:
      label: Hvordan/hvilke ophæng til nationale strategier er til stede?
  - type: markdown
    attributes:
     value: |
       ## FORMKRAV
  - type: checkboxes
    id: checkbox1
    attributes:
      label: Bekræft
      options:
      - label: Kildekoden deles.
  - type: input
    id: input1
    attributes:
     label: Indsæt link
  - type: checkboxes
    id: checkbox2
    attributes:
     label: Bekræft
     options:
       - label: Open Source licenskriterier overholdes.
  - type: input
    id: input2
    attributes:
      label: Indsæt vedtaget licens

