name: Evaluering af produktniveau
description: OS2 arbejder med en tredelt governancemodel, der inddeler produkterne i tre niveauer ud fra organisatorisk og teknisk modenhedsniveau. 
body:
  - type: markdown
    attributes:
      value: |
        ## Relevans
        ### Niveau 1 - Lokal værdi
        Produktets relevans er, om det skaber lokal værdi og potentiel værdi for andre offentlige organisationer. Den lokale værdi er beskrevet og kan overføres til andre.
  - type: checkboxes
    id: checkbox1
    attributes:
      label: Bekræftelse af relevans for Niveau 1
      options:
        - label: Løsningen skal skabe lokal værdi.
        - label: Løsningen skal have potentiel værdi for andre.
  - type: input
    id: input1
    attributes:
      label: Input for Niveau 1

  - type: markdown
    attributes:
      value: |
        ### Niveau 2 - Fælleskommunal værdi
        Værdien er nu ikke længere en potentiel værdi for andre organisationer, men en fælleskommunal værdi.
  - type: checkboxes
    id: checkbox2
    attributes:
      label: ekræftelse af relevans for Niveau 2
      options:
        - label: Løsningen bør have et tværkommunal potentiale.
        - label: Accept fra lokal linjeledelse.
  - type: input
    id: input2
    attributes:
      label: Input for Niveau 2

  - type: markdown
    attributes:
      value: |
        ### Niveau 3 - Nationale strategier
        For Niveau 3 er gældende, at der skal være et ophæng til de nationale strategier. Det betyder, at produktet skal understøtte kommunerne i realisering af de kommunale krav og mål opstillet i de nationale strategier.
  - type: checkboxes
    id: checkbox3
    attributes:
      label: Bekræftelse af relevans for Niveau 3
      options:
        - label: Ophæng til nationale strategier er til stede.
  
  - type: input
    id: input3
    attributes:
      label: Henvisning
    
    - type: markdown
    attributes:
      value: |
        ## Formkrav
        For alle løsninger der deles i OS2-fællesskabet, er der en række formkrav, der som minimum skal efterleves. 
        ### Niveau 1 - Lovformelighed
        Produktets relevans er, om det skaber lokal værdi og potentiel værdi for andre offentlige organisationer. Den lokale værdi er beskrevet og kan overføres til andre.
  
  - type: checkboxes
    id: checkbox1
    attributes:
      label: Bekræftelse af relevans for Niveau 1
      options:
        - label: Kildekoden deles
        - label: Open source licenskriterier overholdes.
        - label: Udbudsregler er overholdt.
        - label: Alm. lovformlighed er overholdt.
        - label: Sikkerhed skal være indtænkt.
        - label: Løsningens formål og værdi skal være beskrevet.
  - type: input
    id: input1
    attributes:
      label: Input for Niveau 1

