name: Evaluering af produktniveau_test
title: "[Produktnavn]: "
description: OS2 arbejder med en tredelt governancemodel, der inddeler produkterne i tre niveauer ud fra organisatorisk og teknisk modenhedsniveau.
body:
  - type: markdown
    attributes:
      value: |
        # R E L E V A N S |
        > [!NOTE] |
        > Highlights information that users should take into account, even when skimming.

  - type: checkboxes
    id: checkbox1
    attributes:
      label: Bekræft relevans
      options:
        - label: Løsningen skaber lokal værdi. (1)
        - label: Løsningen skaber potentielt værdi for andre. (1)
        - label: Løsningen er accepteret af lokal linjeledelse (2)
        - label: Løsningen har tværkommunal potentiale (2)
        - label: Ophæng til nationale strategier er til stede (3)
  
  - type: textarea
    attributes:
      label: Henvis til relevans
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!
      placeholder: |
        Henvisninger til
          - Beskrivelser af gevinster og potentialer
          - Godkendelser, f.eks tilslutningsaftaler 
    validations:
      required: false
