name: Produkt evaulering
description: Skabelon til evaluering af produkt
title: '[Produktnavn]:'
body:
  - type: checkboxes
    id: relevans-tjek
    attributes:
      label: 🎯 Relevans
      description: >-
        Læs mere her:
        https://faq.os2.eu/relevans-produktniveauer-os2-projekter-og-produkter
      options:
        - label: Løsningen skaber lokal værdi.
          required: true
        - label: Løsningen skaber potentielt værdi for andre. (Niveau 1)
          required: false
        - label: Løsningen er accepteret af lokal linieledelse (Niveau 2)
          required: false
        - label: Løsningen har tværkommunalt potentiale (Niveau 2)
          required: false
        - label: Ophæng til nationale strategier er til stede (Niveau 3)
          required: false
  - type: textarea
    id: relevans-henvisning
    attributes:
      label: 🔗 Henvisninger
      description: 'Se eksempler her: https://udfyldt_gevinskort'
      placeholder: Indsæt henvisninger til produktets relevans, værdiskabels og potentiale.
    validations:
      required: true
  - type: markdown
    attributes:
      value: '---'
  - type: checkboxes
    id: formkrav-deling-tjek
    attributes:
      label: 🔄  Deling
      description: >-
        Læs mere her:
        https://faq.os2.eu/formkrav-produktniveauer-os2-projekter-og-produkter
      options:
        - label: Kildekoden deles
          required: true
        - label: Open Source licenskriterier overholdes
          required: true
        - label: Kildekoden placeres på OS2s Github (Niveau 1)
          required: false
        - label: OS2s værktøjer benyttes (Niveau 1)
          required: false
        - label: >-
            Alt kode til det officielle udgivne produkt er  indsendt til
            projektets officielle Os2 ejede repository (Niveau 2)
          required: false
        - label: >-
            Løsningen leveres i containerformat til drift og til videreudvikling
            (Niveau 2)
          required: false
  - type: textarea
    id: formkrav-deling-henvisninger
    attributes:
      label: 🔗 Henvisninger
      description: 'Se eksempler her: ??'
      placeholder: >-
        Indsæt henvisninger til kildekode, licenser og processer for udvikling
        og deling af løsningen.
    validations:
      required: true
  - type: markdown
    attributes:
      value: '---'
  - type: checkboxes
    id: formkrav-kommunikation
    attributes:
      label: 📢 Kommunikation
      description: >-
        Læs mere her:
        https://faq.os2.eu/formkrav-produktniveauer-os2-projekter-og-produkter
      options:
        - label: >-
            Alt officiel kommunikation foregår via OS2s kommunikationskanaler
            (Niveau 1)
          required: false
        - label: Kommunikationsmateriale til strategisk niveau udarbejdes (Niveau 2)
          required: false
        - label: Præsentationsmateriale af løsningen er udarbejdet (Niveau 2)
          required: false
        - label: Lokal politisk kommunikation er udarbejdet (Niveau 3)
          required: false
        - label: National politisk kommunikation er udarbejdet (Niveau 3)
          required: false
  - type: textarea
    id: formkrav-kommunikation-henvisninger
    attributes:
      label: 🔗 Henvisninger
      description: 'Se eksempler på materiale her: ??'
      placeholder: Indsæt henvisninger til publiceret materiale her
    validations:
      required: true
  - type: markdown
    attributes:
      value: '---'
  - type: checkboxes
    id: formkrav-dokumentation-tjek
    attributes:
      label: 📑 Dokumentation
      options:
        - label: >-
            Løsningens formål og værdi er beskrevet i README.md i løsningens
            officielle repository
          required: true
        - label: >-
            Implementerings metode til løsningen er beskrevet i
            GETTING_STARTED.md i det officielle repository (Niveau 1)
          required: false
        - label: >-
            Teknisk dokumentation er placeret under ./docs i løsningens
            officielle repository (Niveau 1)
          required: false
        - label: MANGLER N2 & N3
          required: false
  - type: textarea
    id: formkrav-dokumentation-henvisningner
    attributes:
      label: 🔗 Henvisninger
      placeholder: >-
        Indsæt henvisninger til arkitekturtegninger i det officielle repo,
        tekniske... etc.
    validations:
      required: true
  - type: markdown
    attributes:
      value: '---'
  - type: checkboxes
    id: formkrav-lovformelighed-tjek
    attributes:
      label: ⚖️ Lovformelighed
      description: Læs mere -->
      options:
        - label: Alm. Lovformlighed er overholdt
          required: true
        - label: Udbudsregler er overholdt
          required: true
  - type: textarea
    id: formkrav-lovformelighed-henvisninger
    attributes:
      label: 🔗 Henvisninger
      description: Eksempler -->
      placeholder: Henvisniger til lovformelighed
    validations:
      required: true
  - type: markdown
    attributes:
      value: '---'
  - type: markdown
    attributes:
      value: >-
        This template was generated with [Issue Forms
        Creator](https://issue-forms-creator.netlify.app)
