name: Governance checklist
description: Test
title: "Test"
body:
- type: checkboxes
  id: terms
  attributes:
    label: Code of Conduct
    description: The [codebase] community adheres to the following principles
    options:
      - label: [codebase] is open source.
      - label: Kildekoden er overdraget og er placeret under OS2's github