name: Issue to Markdown

on:
  issues:
    types: [opened]

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Convert issue to markdown
        id: convert
        run: |
          ISSUE_NUMBER=$(jq --raw-output .issue.number "$GITHUB_EVENT_PATH")
          ISSUE_BODY=$(jq --raw-output .issue.body "$GITHUB_EVENT_PATH")

          echo "Converting issue #$ISSUE_NUMBER to markdown..."

          # Replace markdown checkboxes with colored checks or crosses
          MARKDOWN_BODY=$(echo "$ISSUE_BODY" | sed 's/- \[ \]/- ❌/g' | sed 's/- \[x\]/- ✅/g')

          # Write the converted issue body to a markdown file
          echo "$MARKDOWN_BODY" > "./docs/issue-$ISSUE_NUMBER.md"

          echo "::set-output name=issue_number::$ISSUE_NUMBER"

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Convert issue #${{ steps.convert.outputs.issue_number }} to markdown"
          git push
